### ISSUE TITLE
Swipe to go back gesture not working after upgrading to 1.13

### ISSUE THREAD

**Issue by jacksonh** [nathantannar4/Transmission#34]
In Omnivore we are using Transmission for our main library. I just tried updating to 1.1.3 and now I'm no longer able to swipe to dismiss. There's also a bit of a weird transition when i first tap on a presentation link.

We have a custom navigation bar so I'm not sure if that's the reason, the reason we started using Transmission was because our custom navigation bar with the back button hidden prevented the interactive pop before.

This is our presentation link code:

```
struct LibraryItemListNavigationLink: View {
  @EnvironmentObject var dataService: DataService
  @EnvironmentObject var audioController: AudioController

  @ObservedObject var item: Models.LibraryItem
  @ObservedObject var viewModel: HomeFeedViewModel

  var body: some View {
    ZStack {
      LibraryItemCard(item: LibraryItemData.make(from: item), viewer: dataService.currentViewer)
      PresentationLink(
        transition: PresentationLinkTransition.slide(
          options: PresentationLinkTransition.SlideTransitionOptions(edge: .trailing,
                                                                     options:
                                                                     PresentationLinkTransition.Options(
                                                                       modalPresentationCapturesStatusBarAppearance: true
                                                                     ))),
        destination: {
          LinkItemDetailView(
            linkedItemObjectID: item.objectID,
            isPDF: item.isPDF
          )
        }, label: {
          EmptyView()
        }
      )
    }
  }
}
```

can be seen here:  https://github.com/omnivore-app/omnivore/blob/main/apple/OmnivoreKit/Sources/App/Views/Home/Components/LibraryItemListNavigationLink.swift

**Comment by jacksonh** [comment]
Previously we were using `1.0.1`

**Comment by nathantannar4** [comment]
Thanks for the bug report, fixed in `1.1.4`

**Comment by jacksonh** [comment]
Hey @nathantannar4 I noticed that 1.1.4 has the same SHA as 1.1.3 on the releases page, I think maybe this fix never got released.

**Comment by jacksonh** [comment]
I'll create a separate issue just so this doesn't get lost.
