### ISSUE TITLE
DragGesture for .fullscreen

### ISSUE THREAD

**Issue by AndrewSB** [nathantannar4/Transmission#45]
is there an option to enable the same drag gesture that exists for sheets when `transition: .fullscreen` is selected? or do i need to add my own `.gesture(DragGesture...)` and do an `.offset(y:)`?

**Comment by nathantannar4** [comment]
I recommend using the `.slide` transition. Its a custom full screen transition I made that is interactive similar to a sheet presentation. `.fullscreen` is not interactive.

**Comment by AndrewSB** [comment]
got it
