### ISSUE TITLE
Presentation resets whole environment 

### ISSUE THREAD

**Issue by PhilipDukhov** [nathantannar4/Transmission#46]
`PresentedView` content shows `0`, `10` is expected. It doesn't happen with a system `.sheet`.

```swift
struct Issue46: View {
    var body: some View {
        ZStack {

        }
//        .sheet(
        .presentation(
            isPresented: .constant(true)
        ) {
            PresentedView()
        }
        .lineSpacing(10)
    }
}

struct PresentedView: View {
    @Environment(\.lineSpacing) var lineSpacing

    var body: some View {
        Text(lineSpacing.description)
    }
}
```

**Comment by nathantannar4** [comment]
Yea, this is a known limitation. Unfortunately SwiftUI doesn't correctly bridge the environment automatically. Its also not as simple as just copying over the environment that existed from the presenter, as that can override some of the environment values that SwiftUI does setup.

**Comment by PhilipDukhov** [comment]
> Yea, this is a known limitation. Unfortunately SwiftUI doesn't correctly bridge the environment automatically. Its also not as simple as just copying over the environment that existed from the presenter, as that can override some of the environment values that SwiftUI does setup.

I see, thank you😌
