### ISSUE TITLE
Swift 6 support

### ISSUE THREAD

**Issue by allenhumphreys** [nathantannar4/Transmission#47]
The title says it all! I'm sure its on your radar ;-), and its probably not super high priority being WWDC just wrapped up, but I'd be interested to see it supported.

**Comment by nathantannar4** [comment]
Released 1.3.0!

**Comment by allenhumphreys** [comment]
Well I missed that as none of the recent issue titles jumped out as covering this!

**Comment by allenhumphreys** [comment]
@nathantannar4 I wanted to follow up on this after digging a little bit more into it.

An example of what I'm seeing when compiling in Swift 6 mode with all the concurrency checking on looks like this:

<img width="985" alt="Screenshot 2024-06-16 at 12 22 32 PM" src="https://github.com/nathantannar4/Transmission/assets/8225090/90e2feaa-2992-46df-9494-bfa2a624ab95">

**Comment by nathantannar4** [comment]
Oh does the new Xcode not have those on by default? I had fixed a bunch of errors/warnings when building on the new Xcode so I thought that covered everything. Will re evaluate thanks!

**Comment by allenhumphreys** [comment]
Even new projects in Xcode don’t enable Swift 6 language mode which surprised me. And I’m not 100% sure how the project settings affect the dependency settings! Swift 6 is gonna be fun!

**Comment by nathantannar4** [comment]
📦 `1.3.1`
