### ISSUE TITLE
HeroMove Transition for larger views

### ISSUE THREAD

**Issue by Saim-Khan1** [nathantannar4/Transmission#5]
Hi @nathantannar4! Hope you're doing well, I just stumbled across this repo and it's exactly what I've needed for a long time, thanks a lot for doing this!

Just one thing I noticed, for the hero move transition, it only really seems to work well if the source view is fairly small (like the blue square example or the pictures in the grid in your example app). I have some cards in my app that I'd like to animate an expanding transition for (a bit like the cards in the App Store), but it doesn't seem to expand as smoothly (e.g. the height doesn't really animate), and sort of fades instead, like this:

![HeroMove transition](https://i.ibb.co/TBMrgBL/ezgif-3-858f6219a6.gif)

For reference, https://github.com/sebjvidal/UIViewControllerAnimatedTransitioning-Demo has some cards that are almost full-width that seem to expand quite nicely, or the below example:

![App Store card example](https://camo.githubusercontent.com/e22c7c1d73d0b316ac4a29e6dfb37f29a34e8e0b15c8278778b0b2721bfdcdc4/68747470733a2f2f63646e2e6a7364656c6976722e6e65742f67682f6d6172636f7367726973656c6c692f456173795472616e736974696f6e7340343062373037306266323862636136393338323037663637306336663963373663666431363064612f6170705f73746f72655f73686f72742e676966)

If I am doing something wrong, or if there's any way to achieve something like this please let me know! Thanks a lot for your help :)

**Comment by nathantannar4** [comment]
The hero move transition is not feature complete. It's just there as a demonstration of what is possible and so one could adapt it to how they would like it to behave. That's why it's not in the library itself, just the example project. 

You'll need to change the transition code. Currently when it the interaction ends, it fades between the two views.

**Comment by Saim-Khan1** [comment]
Ahh I see, thanks for clarifying. I don't actually use UIKit myself, would you be able to point me to whereabouts it says the views should fade? And I can try and figure something out :)

**Comment by nathantannar4** [comment]
You'll need to learn about `UIViewControllerInteractiveTransitioning` and `UIViewControllerAnimatedTransitioning`. Look at the source code for the heroMove transition in the example and you'll see it.

**Comment by Saim-Khan1** [comment]
Perfect, could you point me to whereabouts in the source code the fade happens? To be honest it's already very close to what I would like to happen anyway, just as I said it needs to expand and shrink properly even with the source view being the size it is (as it does when the source view is smaller, as in the GIF above), as I am not too familiar with UIKit myself would you be able to highlight how I could do this? I was thinking maybe there's some logic in your code that checks for the sizing and behaves accordingly? If not if you could point me in the right direction I would really appreciate it, as long as it doesn't take too much of your time!
