### ISSUE TITLE
Dismiss stops working after multiple invocations on 1.3.1

### ISSUE THREAD

**Issue by jacksonh** [nathantannar4/Transmission#50]
I had to record a video for this one: https://www.loom.com/share/49227ee6ebc6457ca7bd17a35faf443f 

After a few invocations of the PresentationLink in the example (using the swipe from trailing), the Dismiss button stops working. This happens in our app as-well, calling `presentationCoordinator.dismiss` will eventually just stop working until the user uses the slide gesture again to dismiss. 

This was done with iOS17 and happens on device and in the simulator.

**Comment by nathantannar4** [comment]
Thanks for the report! Fixed in 1.3.2

**Comment by jacksonh** [comment]
Thanks, just verified it. Also seems to fix some issues we had on iOS18
