### ISSUE TITLE
Matched Geometry Transition Ignores Scrollview.

### ISSUE THREAD

**Issue by NJMorrow14** [nathantannar4/Transmission#54]
https://github.com/user-attachments/assets/4e34948c-6530-4f0c-aa60-e3d4bd083820

I may be missing something but when using the matched Geometry model is the example app (and in my app I'm trying to build), scrollview gestures are ignored within the created modal. Ideal behavior would be to dismiss when pulling down at top of scrollview and dismissing when pull up at bottom of scrollview. Currently you cannot scroll at all.

**Comment by nathantannar4** [comment]
Fixed in `1.4.4`!
