### ISSUE TITLE
iOS 18: DestinationLink not working with NavigationStack underneath

### ISSUE THREAD

**Issue by byasami** [nathantannar4/Transmission#59]
Hello, big thanks for creating this package! I recently upgraded to iOS 18 and I noticed something that was working before, is no longer working now. Essentially, in the example below, I can't seem to get "NavLink" and "DestinationLink" to both work. 

```
struct ContentView: View {
    var body: some View {
        NavigationStack {
            PresentationLink(transition: .slide(edge: .trailing)) {
                NavigationStack {
                    Test2()
                }
            } label: {
                Text("Press (Transmission)")
            }
            
            NavigationLink("Press (NavLink)") {
                Test3()
            }
        }
    }
}

struct Test2: View {
    var body: some View {
        DestinationLink {
            Test2()
        } label: {
            Text("DestinationLink")
        }
    }
}

struct Test3: View {
    var body: some View {
        NavigationLink("Press (NavLink Nested)") {
            Test3()
        }
    }
}

#Preview {
    ContentView()
}
```

Running version 1.4.8 with Xcode 16.0 and I notice:

iOS 17: 
- Works with both NavigationStacks

iOS 18:
- If both NavigationStacks are present, only NavLink works.
- If only parent NavigationStack is present, only NavLink works.
- If only nested NavigationStack is present, only DestinationLink works.

Thanks in advance!

**Comment by nathantannar4** [comment]
hmm, looks like this is a bug in SwiftUI with `NavigationStack`. I can repo with the `.sheet` modifier as well.

In particular, a `UINavigationController` is not created for the `NavigationStack` when nested

Try with:
```swift
Button {
    isPresented = true
} label: {
    Text("Present (.sheet)")
}
.sheet(isPresented: $isPresented) {
    Test2()
}
```

**Comment by nathantannar4** [comment]
Looking into it!
