### ISSUE TITLE
sheet custom detent: min(.ideal, ctx.maximumDetentValue * 0.5)?

### ISSUE THREAD

**Issue by AndrewSB** [nathantannar4/Transmission#62]
how would I compose a detent for a sheet that's the minimum of half the height of the screen, or the ideal size?

I tried using a `.custom` detent, but I don't see how to get the ideal height, the `ResolutionContext` doesn't seem to have it, so i'm not sure what Float to return from the `.custom` closure

**Comment by AndrewSB** [comment]
ideally, i would have the view being presented passed in as part of the `ResolutionContext`, so I can get it's ideal size

**Comment by nathantannar4** [comment]
Yea I can add this!

**Comment by nathantannar4** [comment]
Added in `1.5.1`!
