### ISSUE TITLE
escape hatch back to UIKit?

### ISSUE THREAD

**Issue by AndrewSB** [nathantannar4/Transmission#63]
is there some way to present a SwiftUI View using a UIViewController presentation API?

on the window's top view controller, for example?

**Comment by nathantannar4** [comment]
Sounds like you're asking for an escape hatch to access the underlying `UIViewController` so that you can use the `present(animated: Bool, completion: ...)` API?

Transmission doesn't have such an escape hatch yet, but you could easily build one I think by utilizing a `UIViewControllerRepresentable`.

> on the window's top view controller, for example?

It sounds like what you're really looking for is a way of presenting a view at the top most level? For that, I'd recommend looking at `WindowLink`. Its an API that presents a new `UIWindow` which its ideal for when you want to show alerts and other top level UI.

Additionally I will add that `PresentationLink` is smart enough to handle the presentation of a view, even if another view is already presented. Meaning, it will dismiss any controllers it needs to in order to present the new view.

**Comment by AndrewSB** [comment]
i'll look at `WindowLink` and report back, thanks @nathantannar4

**Comment by AndrewSB** [comment]
is there an imperative API i can use to present it?

in my case, i get a response back from an API, outside the view layer, and i want to present a sheet. for example:

```swift
func handleAPIResponse(data: Any) {
  // parse, validate
  if requiresAlert {
    // TODO: replace this line with a Transmission bottom sheet
    UIApplication.mainWindow?.rootViewController?.present(UIHostingController(MySwiftUIView()))
  }
}

**Comment by AndrewSB** [comment]
i could put some state in my root view, and write to it from this API response, but i'd prefer to avoid that extra state in one of my root views to drive the `.window(isPresented: myOptionalStateFromAPI, { MySwiftUIView() })`

**Comment by AndrewSB** [comment]
oh wait -- there isn't a `WindowLinkTransition` for sheet, which kind of makes sense.

i don't think this API will work for what I'm trying to accomplish.

I'm going to try adding that state to one of my root views and showing a PresentationLinkModifier through the `View.presentation(isPresented:destination:)` API

**Comment by nathantannar4** [comment]
Perhaps I don't fully understand what you're asking, could you share a pseudo code example of the API you're looking for?

**Comment by AndrewSB** [comment]
i solved this on friday using a `.presentation` on my, here was my entire solution

i can trigger the presentation anywhere like so:

```swift
Task { @MainActor in
    let rootView = await rootCoordinator.swiftUIViewOnceLoggedIn
    withAnimation {
        rootView.store.showAddFriendsSheet = true
    }
}
```

by using a `.presentation` on my root view

```swift
struct LoggedInView: View {
    class Store: ObservableObject {
        @Published public var showAddFriendsSheet = false
    }

    @ObservedObject public var store: Store

    init(logout: @escaping Block) {
        self._store = ObservedObject(initialValue: Store())
        // ...
    }

    var body: some View {
        AnyViewControllerRepresentable(rootVC)
            // ..
            .presentation(
                transition: .sheet(options: PresentationLinkTransition.SheetTransitionOptions(
                    detents: [.custom("ideal-or-half-screen", resolver: { ctx in
                        min(ctx.idealDetentValue(), ctx.maximumDetentValue * 0.75)
                    })],
                    preferredCornerRadius: EditorLayoutConstants.canvasCornerRadius
                )),
                isPresented: $store.showAddFriendsSheet,
                destination: {
                    AddFriendsView()
                }
            )
    }
}
```

**Comment by AndrewSB** [comment]
i appreciate the help, i think others may benefit from a window level sheet presentation API, but i'm set for now

thanks @nathantannar4!

**Comment by nathantannar4** [comment]
What do you mean by window level sheet presentation API?

Were you looking for a way to present a SwiftUI view without it being tied to an `isPresented` binding? Or just an `Options` param to specify that the `PresentationLinkTransition` present on not the current view controller, but the windows top most view controller?

**Comment by AndrewSB** [comment]
the former, i wanted my trigger to look something like 

```swift
Task { @MainActor in
    // await the user to finish logging in, if currently not authenticated
    let _ = await rootCoordinator.swiftUIViewOnceLoggedIn

    // present this Transmission sheet on top of the window, imperatively. with Transmission internally handling the state by queuing or replacing it's own window sheet state
    UIApplication.shared.topViewController.presentSheet(
        view: { AddFriendsView() },
        options: PresentationLinkTransition.SheetTransitionOptions(
            detents: [.custom("ideal-or-half-screen", resolver: { ctx in
                min(ctx.idealDetentValue(), ctx.maximumDetentValue * 0.75)
            })]
    )
```

instead of choosing a SwiftUI view near the top of the hierarchy, and managing the `isPresented` state myself

no idea if this is a good design, but this is kind of like the API my toast library provides
