### ISSUE TITLE
Presenting multiple sheet.

### ISSUE THREAD

**Issue by DmitriyTerekhin** [nathantannar4/Transmission#69]
Is it possible to present one sheet over already presented sheet? Looks like not...

**Comment by nathantannar4** [comment]
Yes it's possible, but you need to present the 2nd sheet from the view of the 1st sheet. Transmission follows UIKit presentation APIs and UIKit disallows presenting a new `UIViewController` on one that is already presenting a `UIViewController`.

**Comment by nathantannar4** [comment]
I can add an option flag to `PresentationLinkTransition.Options` to instead present on the top most view

**Comment by nathantannar4** [comment]
Fixed in `1.7.1`
