### ISSUE TITLE
Sheet presentation with `.ideal` detent crashes

### ISSUE THREAD

**Issue by vpontis** [nathantannar4/Transmission#8]
We've seen crashes with partial sheets w/ the ideal detent. It's not reliably reproducible and the logs aren't good. 

I thought to open this issue in case it is useful and if I find more data / crash logs / ideas, I'll add them here :)

![CleanShot 2023-10-04 at 17 36 53@2x](https://github.com/nathantannar4/Transmission/assets/1319079/7474b08c-3f6e-40ea-8743-158cc67449c7)

**Comment by nathantannar4** [comment]
I did make some improvements in `0.1.25` that _could_ have helped with this. Been trying to reproduce this but no luck yet. Do you know which iOS version this is crashing on?

**Comment by vpontis** [comment]
We are on `0.1.26` — I think it is happening less but that's totally anecdotal.

Re iOS version — I've seen it on iOS 17 and iOS 17 beta. I haven't been testing 16 as much. 

I think I caught it in simulator + XCode yesterday. I'm 90% sure it's the same issue, here are screenshots of the debugger:

![CleanShot 2023-10-04 at 19 26 44@2x](https://github.com/nathantannar4/Transmission/assets/1319079/3454664b-6ff4-4d53-a69d-f5f003aa5827)
![CleanShot 2023-10-04 at 19 26 42@2x](https://github.com/nathantannar4/Transmission/assets/1319079/db3e7f7b-7385-4cb6-9404-8bba0334a1a7)
![CleanShot 2023-10-04 at 19 26 40@2x](https://github.com/nathantannar4/Transmission/assets/1319079/88424519-d240-440d-83e4-c5078df8d23a)

**Comment by nathantannar4** [comment]
@vpontis curious if you have still seen this on 0.1.27 or higher?

**Comment by vpontis** [comment]
> @vpontis curious if you have still seen this on 0.1.27 or higher?

Anecdotally it's been better! I'll dig into some of the crashes this week.

**Comment by nathantannar4** [comment]
Closing for now, but let me know if you see the issue again

**Comment by vpontis** [comment]
It's either much better or totally solved now.
